# https://github.com/araffin/rl-baselines-zoo/blob/master/hyperparams/sac.yml#L116
# SAC Configuration for CarRacing-v3

# Environment settings
env_id: CarRacing-v3
use_grayscale: true
use_frame_stack: true
use_skip_frame: true
use_throttle_action: true
n_stack: 4

# Training settings
max_timesteps: 500000
start_steps: 20000 # Random warmup steps
checkpoint_interval: 5000  # How often to evaluate + record video
log_freq: 1000

# Agent hyperparameters
batch_size: 64
gamma: 0.99
tau: 0.005
alpha: 0.1
automatic_entropy_tuning: true
policy_learning_rate: 0.0003
q_learning_rate: 0.0003
alpha_learning_rate: 0.0003
policy_weight_decay: 0.0001
q_weight_decay: 0.0001
alpha_weight_decay: 0.0001

# Network architecture
q_hidden_dims: [ 512, 256, 256 ]
policy_hidden_dims: [ 512, 256, 256 ]

# Replay buffer
buffer_size: 50000

# Training dynamics
train_freq: 1  # Update every N steps
gradient_steps: 1  # Number of gradient updates per training step

# Episode settings
max_ep_len: 1000

# Logging
project_name: rl-training
run_name: sac-carracing-v3-rl-zoo
record_video: true
